### ISSUE TITLE
Registration: sendRegistrationMail not working - throwing exception

### ISSUE THREAD

**Issue by ItsTommyGun** [thyseus/yii-user-management#202]
When trying to register I always get the exception
**"Email is not set when trying to send Registration Email"**
see: registration/controllers/YumRegistrationController.php(106)
'<code>'if (!isset($user->profile->email))
throw new CException(Yum::t('Email is not set when trying to send Registration Email'));'</code>'

Really can't figure it out, anyone has an idea about that?

**Comment by thyseus** [comment]
It seems like the profile did not get created properly when the user got created/registered. The 'registration' submodule depends on the 'profile' submodule, so i assume you have the module activated. Can you check if the profile is created for the user and supply a stack trace? Thanks.

**Comment by tonsenson** [comment]
At first, thanks for answering that quick!

How should I deliver the stack trace?
/protected/modules/registration/controllers/YumRegistrationController.php(89): YumRegistrationController->sendRegistrationEmail(YumUser)
'<code>'
84                 $user = new YumUser;
85                 $user->register($form->username, $form->password, $profile);
86                 
87 
88 
89                 $this->sendRegistrationEmail($user);
90                 Yum::setFlash('Thank you for your registration. Please check your email.');
91                 $this->redirect(Yum::module()->loginUrl);
92             }
93         } 
94 
'</code>'

[...]

/index.php(13): CApplication->run()
'<code>'
08 defined('YII_DEBUG') or define('YII_DEBUG',true);
09 // specify how many levels of call stack should be shown in each log message
10 defined('YII_TRACE_LEVEL') or define('YII_TRACE_LEVEL',3);
11 
12 require_once($yii);
13 Yii::createWebApplication($config)->run();
'</code>'

And how to check for profile creation? Tried to look for email being saved; it is saved in $profile, so that should not be the problem?
